version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
    - spicelang/vscode-extension-team
  assignees:
    - spicelang/vscode-extension-team